"""
SecureDocAI — Detection Constants
==================================
Shared lists and constants used across Regex and NER detectors
to improve precision and reduce false positives.
"""

# ── PII Blacklist ──
# Common non-PII terms that detectors frequently misidentify as Persons or Organizations.
# These will be explicitly filtered out from detection results.
PII_BLACKLIST: set[str] = {
    # Tech Brands / Tools / Frameworks
    "GITHUB", "LINKEDIN", "BITBUCKET", "DOCKER", "KUBERNETES", "PYTHON", "JAVA", "ORACLE", 
    "AWS", "GCP", "AZURE", "POSTGRESQL", "MYSQL", "MONGODB", "REDIS", "REACT", "NODE", "FLASK",
    "FASTAPI", "FAST API", "SPRING", "HIBERNATE", "POSTMAN", "GIT", "GOOGLE", "MICROSOFT",
    "LOOKER", "DEEPGRAM", "GEMINI", "GPT", "OPENAI", "CHROME", "CHIPS", "DEVOPS", "CI/CD",
    "CODEZEN", "SAFELENS", "DOCUSENSE", "TALENTFLOW", "AIVA", "DEEPGRAM-ASR", "PIOPIY",
    "STREAMLIT", "GRADIO", "PROMPT", "ENGINEERING", "SEMANTIC", "SEARCH", "BBOX", "JSON", 
    "CSV", "REST", "API", "CLOUD", "SQL", "NOSQL", "BIGQUERY", "FIRESTORE", "GCS", "S3", 
    "EC2", "FAISS", "CHROMADB", "PINECONE", "TRANSFORMERS", "MiniLM", "SMOTE", "AUC", "ROC",
    "AST", "PARSING", "EMBEDDINGS", "CLI", "DEEPGRAM", "AIVA", "REST", "CRUD",

    # Common Resume/Academic/Job Terms
    "MBA", "BTECH", "B.TECH", "PHD", "MS", "MTECH", "BCA", "MCA", "HR", "TA", "QA",
    "SUMMARY", "EXPERIENCE", "SKILLS", "EDUCATION", "PROJECTS", "ACHIEVEMENTS", "LANGUAGES",
    "CERTIFICATIONS", "OBJECTIVE", "INTERESTS", "PROFILE", "PROFESSIONAL", "ASSOCIATE",
    "SPECIALIZING", "FRAMEWORKS", "ML", "AI", "NLP", "LLM", "RAG", "OCR", "NER", "PII",
    "SCALABLE", "ENTERPRISE", "QUANTIZED", "AGILE", "GITLAB", "FIGMA", "DATA", "SCIENTIST",
    "ENGINEER", "ENGINEERING", "INTERN", "SCIENCE", "ANALYTICS", "SYSTEM", "SOLUTIONS", 
    "ARCHITECTURE", "BUILDING", "EXPERT", "DEVELOPING", "APPLICATIONS", "COMPUTING", 
    "INFRASTRUCTURE", "OPERATIONS", "INTELLIGENCE", "SAFETY", "PRIVACY", "SCORE", "RISK", 
    "MATCHING", "FULL", "STACK", "EVALUATION", "STRUCTURE", "DESCRIPTION", "REASONING", 
    "DEPLOYMENT", "PRACTICES", "PRACTICED", "FOLLOWED", "STRUCTURED", "CODING", "DEVELOPMENT",
    "SENIOR", "JUNIOR", "LEAD", "MANAGER", "DIRECTOR", "FOUNDER", "CEO", "CTO", "VP", "LABS",
    "PVT", "LTD", "PRESENT", "MARCH", "JANUARY", "FEBRUARY", "AUGUST", "OCTOBER", "CGPA",
    "UNIVERSITY", "COLLEGE", "INSTITUTE", "SCHOOL", "FOUNDATION", "CERTIFICATION",
    "LOGISTIC", "REGRESSION", "FOREST", "RANDOM", "TUNING", "MODEL", "FEATURE", "SENTENCE",
    "QUANTIZED", "ENTERPRISE", "PRODUCTION", "GRADE", "BUILDING",
    "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY",
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC",
    "DATA SCIENTIST", "DATA SCIENCE", "SOFTWARE ENGINEER", "BACKEND INTERN", "PRE-SALES",
    "PRE SALES", "DEVOPS", "RESEARCHER", "ANALYST", "DEVELOPER", "ARCHITECT", "CONSULTANT",
    "ICFAI", "MOTIVITY", "DATAQUAD", "PVT LTD", "LTD.", "PVT.", "UNIVERSITY",
    "COMPUTER SCIENCE", "INFORMATION TECHNOLOGY", "MECHANICAL ENGINEERING",
    "LOAN", "AGREEMENT", "BORROWER", "LENDER", "APPLICANT", "DETAILS", "FATHER", "MOTHER",
    "SPOUSE", "RELATIONSHIP", "GENDER", "FORMAT", "CASE", "MIXED", "LEGAL", "CONFIRMATION",
    "EMPLOYER", "EMPLOYEE", "EMPLOYMENT", "INFORMATION", "SALARY", "ANNUAL", "AMOUNT", "TENURE", 
    "IFSC", "AADHAAR", "PAN", "ACCOUNT", "NUMBER", "MOBILE", "ALTERNATE", "CONTACT", "EMAIL", 
    "PERSONAL", "PERMANENT", "ADDRESS", "OFFICE", "SIGNATURE", "DECLARATION", "HEREBY", 
    "CONFIRM", "TRUE", "CORRECT", "BETWEEN", "MADE", "DISBURSEMENT", "EMI", "RATE", "PERCENT", 
    "ANNUM", "TITLE", "LABEL", "HEADER", "FOOTER", "PAGE", "TOTAL", "SUBTOTAL", "BALANCE",
    "DUPLICATE", "STATEMENT", "BANK", "HDFC", "ICICI", "SBI", "AXIS", "KOTAK", "CITI", 
    "HSBC", "BARCLAYS", "MINIMUM", "MAXIMUM", "AVAILABLE", "CREDIT", "LIMIT", "CASH", 
    "DUE", "DATE", "AMOUNT", "CHARGES", "INCURRED", "PLEASE", "ENSURE", "DALLY", "REDUCING", 
    "METHOD", "HOTLIST", "NETBANKING", "PHONBANKING", "LOCATE", "RESERVE", "INDIA", 
    "FACILITATE", "EFFECTIVE", "INFORMED", "ASSESSMENT", "CONDUCT", "STATUTORY", "BODIES", 
    "ACCORDANCE", "VOLUNTARY", "CODES", "PRESCRIBED", "COMMITMENT", "PLATINUM", "CONSUMER", 
    "PRIVILEGE", "SERVE", "OUTSTANDING", "AUTHORISED", "REGULARISE", "WITHOUT", "THESE", 
    "WITHIN", "THROUGH", "FOLLOWING", "PREVIOUS", "REVISED", "TERMS", "CONDITIONS", "GENERAL", 
    "SCHEDULE", "REWARD", "POINTS", "WEBSITE", "CARD", "CARDS", "ACCOUNT", "ACCOUNTING",
    "OFFICER", "MANAGER", "DIRECTOR", "ADMINISTRATOR", "DEPARTMENT", "DIVISION", "BRANCH",
    "JAIPUR", "CHENNAI", "HYDERABAD", "BANGALORE", "MUMBAI", "DELHI", "PUNE", "KOLKATA",
    "RAJASTHAN", "TAMIL NADU", "TELANGANA", "KARNATAKA", "MAHARASHTRA", "GUJARAT",
    "HHSN", "GSTIN", "GST", "IGST", "CGST", "SGST", "TAX", "INVOICE", "BILL", "RECEIPT",
    "PAYMENT", "TRANSACTION", "REFERENCE", "DESCRIPTION", "MERCHANT", "CATEGORY",
    "DEBIT", "CREDIT", "CURRENCY", "INR", "USD", "EUR", "GBP", "SUCCESSFUL", "FAILED",
    "PENDING", "COMPLETED", "SETTLED", "REVERSED", "VOID", "REFUND", "AUTHORIZED",
    "PAYTM", "GSTIN", "HSN", "GST", "CSB", "BCSBI", "CICS", "CIC", "AAN", "TOTAL", 
    "MINIMUM", "MAXIMUM", "AMOUNT", "DUE", "DATE", "CASE", "NOTE", "PLEASE", "WRITE",
    "LETTER", "DIVISION", "DIVISIONAL", "MANAGER", "AVAILABLE", "LIMIT", "CHARGES",
    "IN", "NO", "FOR", "TO", "THE", "AND", "WITH", "FROM", "ON", "AT", "BY", "OF",
    "CARD", "NUMBER", "NO.", "AAN:", "CARD:", "NAME:", "EMAIL:", "ADDRESS:", "MOBILE:", "PHONE:"
}
